#+title: Emacs config
#+property: header-args :tangle config.el

* Default Config
The default ~config.el~ packaged with ~doom-emacs~ already comes with some sensible configurations.

#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Doom exposes five (optional) variables for controlling fonts in Doom:
;;
;; - `doom-font' -- the primary font to use
;; - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
;; - `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;; - `doom-unicode-font' -- for unicode glyphs
;; - `doom-serif-font' -- for the `fixed-pitch-serif' face

;; See 'C-h v doom-font' for documentation and more examples of what they
;; accept. For example:

;;(setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
;;      doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))
;;
;; If you or Emacs can't find your font, use 'M-x describe-font' to look them
;; up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
;; refresh your font settings. If Emacs still can't find your font, it likely
;; wasn't installed correctly. Font issues are rarely Doom issues!

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:

;; (setq doom-theme 'doom-gruvbox)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
;; (setq org-directory "~/org/")

;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

;; Add load-paths for custom packages and modules
;; (load-path wasn't updated for a few modules)
#+end_src

** Identification
Some functionality uses this to identify the user, e.g. GPG configuration, email clients, file templates and snippets. It is optional.

#+begin_src emacs-lisp
(setq user-full-name "aZul"
      user-mail-address "fmdcosta.piano@gmail.com")
#+end_src

* Emacs behaviour
** Windowing system
Over the few years I've been using Doom-Emacs I found I'm very particular with the layout of my windows. Typically I use the 2 vertical window setup, or 1 vertical window on the right and 2 horizontal ones on the left.

I'd like to write a command that sets up these layouts and also a way to point to the windows with a number.
* Appearance
** Font
Set the font and font size.

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Firacode Nerd Font Mono" :size 16))
#+end_src

** Doom Theme
Set ~doom-everforest~ as the default doom theme.

#+begin_src emacs-lisp
(setq doom-everforest-background "soft")  ; or hard (defaults to soft)
(setq doom-everforest-light-background "soft") ; or hard (defaults to soft)
;; (setq doom-theme 'doom-everforest) ; dark variant
#+end_src

Changing to an already loaded theme doesn't update them. A hacky solution is to force an update to ~doom-theme~ after ~consult-theme~ finishes execution. This was based on a fix from [[https://github.com/doomemacs/doomemacs/issues/7511#issuecomment-1869710558][this github comment]].

#+begin_src emacs-lisp
(defadvice! zcfg--set-doom-theme-after-consult-a (theme)
  "Sets `doom-theme' to theme regardless of `consult-theme' implementation.
currently, `doom-theme' isn't updated when selecting an already loaded
theme.

This fix is based on
https://github.com/doomemacs/doomemacs/issues/7511#issuecomment-1869710558"
  :after #'consult-theme
  (setq doom-theme theme))
#+end_src

*** Day/Night theme
Doom doesn't come with a day/night theme system by default, one that automatically updates at a specific time of the day.

#+name: set-day-night-themes-vars
#+begin_src emacs-lisp
(defgroup z-config nil
  "My own configuration"
  :group 'emacs)

(defcustom zcfg-day-theme 'doom-homage-white
  "Azul config's daytime theme"
  :group 'z-config)

(defcustom zcfg-night-theme 'doom-everforest
  "Azul config's nighttime theme"
  :group 'z-config)

(defcustom zcfg-contrast-theme 'doom-1337
  "Azul config's contrast theme"
  :group 'z-config)

(defcustom zcfg-sunrise-time "07:00"
  "The time of sunrise. Has to be in HH:mmam/pm format - e.g. 07:00"
  :type '(string)
  :group 'z-config)

(defcustom zcfg-sunset-time "17:00"
  "The time of sunset. Has to be in HH:mmam/pm format - e.g. 18:00"
  :type '(string)
  :group 'z-config)

(defun zcfg--switch-day-night-themes (time)
  "Switch between day and night themes.
E.G. after sunrise this function updates the theme to `zcfg-day-theme' whether
that's the current theme or not. Likewise, for the night theme. TIME is one of
two symbols `day' or `night'"

  (cond ((eq time 'day)
         (unless (equal doom-theme zcfg-day-theme)
           (load-theme zcfg-day-theme :no-confirm)))
        ((eq time 'night)
         (unless (equal doom-theme zcfg-night-theme)
           (load-theme zcfg-night-theme :no-confirm)))))

(let*
    ((parse-fn (lambda (time)
                 (let* ((time-val (parse-time-string time)))
                   (+ (* (decoded-time-minute time-val) 60)
                      (* (decoded-time-hour time-val) 60 60)))))
     (sunrise-seconds (funcall parse-fn zcfg-sunrise-time))
     (sunset-seconds (funcall parse-fn zcfg-sunset-time))
     (current-timeval (decode-time (current-time)))
     (current-seconds (+ (* (decoded-time-minute current-timeval) 60)
                      (* (decoded-time-hour current-timeval) 60 60)))
     (after-sunrise-clause (< sunrise-seconds current-seconds))
     (after-sunset-clause (< sunset-seconds current-seconds))
     (between-sunrise-sunset-clause (and after-sunrise-clause
                                         (not after-sunset-clause))))

;; (run-at-time t sunrise-seconds #'zcfg--switch-day-night-themes 'day)
;; (run-at-time t sunset-seconds #'zcfg--switch-day-night-themes 'night)

(if between-sunrise-sunset-clause
    (setq doom-theme zcfg-day-theme) (setq doom-theme zcfg-night-theme)))


(run-at-time zcfg-sunrise-time 86400 #'zcfg--switch-day-night-themes 'day)
(run-at-time zcfg-sunset-time 86400 #'zcfg--switch-day-night-themes 'night)
#+end_src

** Buffer appearance
Set the gutter line number mode. if set to `nil', numbers are disabled. For relative line numbers, set this to `'relative'.

But there's an issue when buffers have their contents folded. In those cases the relative numbers don't show exactly the number of lines, so that `20j` might not go down 20 lines.

# TODO(azul) Need to look at the value 'visual
#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src

I'm a big proponent of adhering to a 80 character column limit for coding, as it easily allows for a 2 window setup.
#+begin_src emacs-lisp
(global-display-fill-column-indicator-mode)
#+end_src

* Keybindings
** org-mode
#+begin_src emacs-lisp
(map! :after org
      :map org-mode-map
      :localleader
      (:prefix ("B" . "org-babel")
       :desc "tangle" :nv "t" #'org-babel-tangle))
#+end_src

One could, I certainly did, expect that the ~prefix~ keyword didn't have to be encircled in a list. But this is due to the way that doom implements ~map!~, and it's not mentioned in their docs.

* Major modes config
** org-mode
The ~org-directory~ variable must be set before org-mode loads.
#+begin_src emacs-lisp
(setq org-directory "~/org/")
#+end_src

* Minor modes config
** evil-mode
*** evil-escape
Set up an escape key sequence for evil-mode to quit insert mode.
#+begin_src emacs-lisp
(setq evil-escape-key-sequence "fj")
(setq evil-escape-delay 0.20)
#+end_src

** recentf-mode
Add files to ~recentf~ every time that a buffer is loaded from a file.
#+begin_src emacs-lisp
(add-hook 'find-file-hook 'recentf-save-list)
#+end_src

** which key
This option is added so which-key popup shows all the options.
#+begin_src emacs-lisp
(setq which-key-allow-imprecise-window-fit nil)
#+end_src

* Programming environments
** Python
*** Python venv
While one could possibly use doom's pyenv module extension, or some solution
using direnv (about which i haven't read much on yet), this solution is an
quick and dirty fix.

#+begin_src emacs-lisp
(defun zcfg/activate-python-venv (venv-path)
  "Activate a python's virtual environment which was set up using its standard
library module venv.

The activation is achieved by checking if the given directory is named \".venv\""

  (let* ((venv-exists (file-exists-p venv-path)))
    (if venv-exists
      (progn
        (setq-local process-environment (copy-sequence
                                         process-environment))
        (setenv "path" (concat (expand-file-name venv-path)
                               "/bin:"
                               (getenv "path")))
        (setenv "pythonpath" (concat (expand-file-name venv-path) "/lib"))
        (setenv "virtual_env" venv-path)
        (setq-local lsp-pylsp-plugins-jedi-environment venv-path)
        (message "azul config: Activating python venv in %s" venv-path))
      (message "Didn't find a python venv directory!"))))
#+end_src

*** Poetry
I found a bug in the ~poetry~ emacs wrapper on this [[https://github.com/cybniv/poetry.el/blob/1dff0d4a51ea8aff5f6ce97b154ea799902639ad/poetry.el#L901][commit]], which might be
the reason why the wrapper isn't detecting ~poetry~ projects. What happens
is the wrapper is expecting that ~pyproject.toml~ contains a line with
~[tools.poetry]~. That is being abandoned in favor of
~[project.dependencies]~.

#+begin_src emacs-lisp
(after! poetry
  (defadvice! zcfg--poetry-find-project-root-a (oldfn &rest args)
    "Advice for finding the root of a poetry project.

The original `poetry-find-project-root' currently has a bug where it expects
the pyproject.toml file to contain a line with [tools.poetry]. That practice
is being abandoned in favor of different structure, which is being accounted
by this advice."
    :around #'poetry-find-project-root
    (or poetry-project-root
        (when-let* ((root (locate-dominating-file default-directory
                                                  "pyproject.toml"))
                    (pyproject-contents
                     (with-temp-buffer (insert-file-contents-literally
                                        (concat (file-name-as-directory root)
                                                "pyproject.toml"))
                                       (buffer-string)))
                    (_ (string-match "^\\[project\\]" pyproject-contents)))
          (setq poetry-project-root root)))))
#+end_src

* Miscellaneous
** Imenu
The default way that ~consult~ presents the ~imenu~ item list is not necessarily in order of appearance. But I'd like a way to quickly navigate through the buffer using the items as a "table of contents" of sort.

Currently, the list is being flattened, but I might change my mind on that in the future.

#+begin_src elisp
(defun zcfg/consult-imenu-toc ()
  "Select item from flattened and sorted `imenu' with preview.

The items are listed sorted according to their appearance in the buffer.

See also `consult-imenu'."
  (interactive)
  (consult-imenu--select
   "Go to item: "
   (consult--slow-operation "Building Imenu..."
     (zcfg--imenu-items-pos-sorted))))

(defun zcfg--imenu-items-pos-sorted ()
  "Return imenu items in order of buffer position.

If the items haven't been indexed yet, the indexation is executed."

;;; The cache may have not been built yet
  (unless (equal (car consult-imenu--cache) (buffer-modified-tick))
    (setq consult-imenu--cache
          (cons (buffer-modified-tick) (consult-imenu--compute))))

  (let* ((items (cdr consult-imenu--cache)))
    (seq-sort #'zcfg--imenu-item-less-than items)))

(defun zcfg--imenu-item-less-than (first-item second-item)
  ""
  (let* ((first-item-marker-pos (marker-position (cdr first-item)))
         (second-item-marker-pos (marker-position (cdr second-item))))
    (< first-item-marker-pos second-item-marker-pos)))
#+end_src

~consult-imenu~ is not loaded at startup by emacs, which requires this:

#+begin_src elisp
(autoload 'consult-imenu--select "consult-imenu")
#+end_src

* TODO
Turn off a few minor modes like highlight-numbers in buffers with LSP mode turned on

Add for..of snippet to typescript and javascript language servers

Completion options don't fuzzy find
