- name: Install zsh
  ansible.builtin.apt:
      name: zsh
      state: present
  become: yes

- name: Install emacs
  become: yes
  ansible.builtin.apt:
      name: emacs
      state: present

- name: Install fd-find
  become: yes
  ansible.builtin.apt:
      name: fd-find
      state: present

- name: Install ripgrep
  become: yes
  ansible.builtin.apt:
      name: ripgrep
      state: present

- name: Install fzf
  become: yes
  ansible.builtin.apt:
      name: fzf
      state: present

- name: Install htop
  become: yes
  ansible.builtin.apt:
      name: htop
      state: present

- name: Install stow
  become: yes
  ansible.builtin.apt:
      name: stow
      state: present

- name: Git clone doom-emacs
  ansible.builtin.git:
      repo: "https://github.com/doomemacs/doomemacs"
      dest: "{{ doom_emacs_install_path }}"
      depth: 1

# XXX(azul) Likely to remove this
# - name: Run doom install
#   ansible.builtin.command:
#     argv:
#         - "{{ doom_bin }}"
#         - "install"
#         - "--force"

- name: Create home bin directory
  ansible.builtin.file:
      path: "{{ bin_folder }}"
      state: directory
      mode: '0755'

- name: Create temp directory
  ansible.builtin.file:
      path: "{{ tmp_folder }}"
      state: directory
      mode: '0755'

- name: Download oh-my-zsh installer script
  ansible.builtin.get_url:
      url: "{{ omz_installer_url }}"
      dest: "{{ omz_installer_path }}"

- name: Run oh-my-zsh installer
  ansible.builtin.script:
      cmd: "{{ omz_installer_path }} --unattended"
      executable: sh

- name: Download zellij pre-built bin
  ansible.builtin.get_url:
      url: "{{ zellij_tar_bin_url }}"
      dest: "{{ zellij_tar_bin_path }}"

- name: Unarchive zellij pre-built bin
  ansible.builtin.unarchive:
      src: "{{ zellij_tar_bin_path }}"
      dest: "{{ bin_folder }}"
      remote_src: yes

- name: Delete temp directory
  ansible.builtin.file:
      path: "{{ tmp_folder }}"
      state: absent
